---
# main.yml

#- name: Install base packages
#  hosts: "{{ host | default('localhost') }}"
#  roles: 
#    - common

- name: Setup Shell
  hosts: "{{ host | default('localhost') }}"
  roles: 
    - shell
