---
# roles/vscode/tasks/main.yml 

- name: Create a default VSCode configuration
  template:
    src: templates/vscode-settings.json.j2
    dest: /Users/{{ lookup('env', 'USER') }}/Library/Application Support/Code/User/settings.json
    owner: "{{ lookup('env', 'USER') }}"
    force: yes

- name: Install VSCode extensions
  shell: code --install-extension {{ item }}
  with_items:
    - aaron-bond.better-comments
    - adpyke.codesnap
    - alefragnani.project-manager
    - almenon.arepl
    - Boto3typed.boto3-ide
    - christian-kohler.path-intellisense
    - codezombiech.gitignore
    - cstrap.python-snippets
    - donjayamanne.git-extension-pack
    - donjayamanne.githistory
    - donjayamanne.python-environment-manager
    - donjayamanne.python-extension-pack
    - eamodio.gitlens
    - hbenl.vscode-test-explorer
    - kaih2o.python-resource-monitor
    - KevinRose.vsc-python-indent
    - littlefoxteam.vscode-python-test-adapter
    - mechatroner.rainbow-csv
    - mintlify.document
    - ms-azuretools.vscode-docker
    - ms-python.black-formatter
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
    - ms-vscode-remote.remote-containers
    - ms-vscode.test-adapter-converter
    - njpwerner.autodocstring
    - njqdev.vscode-python-typehint
    - oderwat.indent-rainbow
    - streetsidesoftware.code-spell-checker
    - traBpUkciP.wolf
    - vscodevim.vim
    - wholroyd.jinja
    - xirider.livecode
    - ziyasal.vscode-open-in-github