---
# roles/common/tasks/main.yml 

# Brew
- name: Install brew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: yes
  loop: "{{ brew_packages }}"

# Cask packages
- name: Install brew CASK packages
  community.general.homebrew_cask:
    name: "{{ item }}"
    install_options: 'cask,appdir=/Applications'
    state: present
  loop: "{{ brew_cask_packages }}"
