---
- copy: src=vscode.repo
    dest=/etc/yum.repos.d/vscode.repo
    owner=root group=root mode=644

- name: Install Visual Studio Code
  yum: pkg=code state=installed

- sysctl: 
    name: fs.inotify.max_user_watches
    value: 524288
    sysctl_set: yes 
    state: present 
    reload: yes 


