---
# roles/machine_learning/tasks/main.yml


- name: Install PIP packages
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3
  with_items:
    - streamlit
    - streamlit-extras
    - watchdog
    - pylint
    - python-dotenv
    - requests
    - setuptools
    - six
    - urllib3
    - requests
    - virtualenv
    - ipython
    - tiktoken
    - weaviate-client
    - black
    - boto3
    - openai
    - llama-index
    - llama-index[local_models]
    - llama-index[query_tools]
    - datasets
    - langchain 
    - pandasai

- name: Install PIP packages with User args
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3
  with_items:
    - numpy
    - scipy
    - matplotlib
    - ipython
    - jupyter
    - pandas
    - sympy
    - nose

- name: Install latest PIP
  ansible.builtin.pip:
    name: pip
    executable: pip3
    state: latest
