---
# roles/common/vars/main.yml 

brew_packages: 
  - ansible
  - gnupg
  - curl 
  - htop 
  - openssl 
  - python 
  - sqlite 
  - tree 
  - wget 
  - jq 
  - nmap 
  - iperf 
  - httpie 
  - git 
  - bash-completion 
  - nvm
  - pnpm
  - awscli 
  - coreutils 
  - unzip
  - hashicorp/tap/packer
  - hashicorp/tap/terraform
  - terragrunt
  - yq
  - pre-commit
  - imagemagick
  - pyenv
  - trino
  - s3cmd
  - cmake
  - protobuf
  - rust
  - podman
  - uv
  - gh
  - glab
  - fzf
  - ruff

brew_tap_packages:
  - hashicorp/tap

brew_cask_packages:
  - obs
  - stats
  - cursor
  - grammarly-desktop
  - postman
  - spotify
  - rar
  - iterm2
  - google-chrome
  - firefox
  - discord
  - keybase
  - signal
  - zoom
  - vlc
  - microsoft-teams
  - microsoft-office
  - microsoft-auto-update
  - microsoft-edge
  - font-fira-code
  - lm-studio
  - tableplus
