---
# roles/shell/tasks/main.yml 

- name: Install Oh My ZSH
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: "/Users/{{ lookup('env', 'USER') }}/.oh-my-zsh"

- name: Set ZSH as the default shell
  shell: chsh -s $(which zsh) {{ lookup('env', 'USER') }}
  become: true

- name: "Create a default ZSH configuration"
  template:
    src: templates/.zshrc.j2
    dest: /Users/{{ lookup('env', 'USER') }}/.zshrc
    owner: "{{ lookup('env', 'USER') }}"
    force: yes

- name: Verify if we cloned Powerlevel10k before 
  stat: 
    path: "$HOME/.oh-my-zsh/custom/themes/powerlevel10k"
  register: p10k_state

- name: Check if plugins exist
  stat: 
    path: "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  register: zsh_suggest_state

- name: Check if plugins exist
  stat: 
    path: "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  register: zsh_highlights_state

- name: Install Powerlevel10k 
  shell: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
  when: not p10k_state.stat.exists

- name: Install zsh-autosuggestions
  shell: git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
  when: not zsh_suggest_state.stat.exists

- name: Install zsh-syntax-highlighting
  shell: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
  when: not zsh_highlights_state.stat.exists

